### PR TITLE
fix install script

### PR DESCRIPTION
**Pull request by pravdomil**
...

### CODE REVIEW

**Comment by ldd** [comment]
Thanks for the pull request!
This is interesting. I'll take a look at it as soon as possible

**Comment by ldd** [comment]
aha!
The problem is that on npm the package is named `gatsby-source-github-api` (`gatsby-source-github` already existed)

On the `Readme.md` it says `gatsby-source-github`.

so if you can, update your pull request to say `gatsby-source-github-api`

**Comment by pravdomil** [comment]
Maybe rename your github repository to `ldd/gatsby-source-github-api` to match the plugin name

**Comment by ldd** [comment]
done! and thanks, I'll accept the pull request now 👍

**Pull request merged**
